//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Workshop_Automation_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Service
    {
        public int Service_Id { get; set; }
        public Nullable<int> App_No { get; set; }
        public string Status { get; set; }
        public string Customer_Suggestion { get; set; }
        public string Surveyor_Suggestion { get; set; }
    }
}
