//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Workshop_Automation_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Appointment_No { get; set; }
        public Nullable<int> Bay_No { get; set; }
        public string Vehicle_Reg_No { get; set; }
        public string Customer_Mobile_No { get; set; }
        public string Date { get; set; }
        public string Slot { get; set; }
        public string Miles { get; set; }
        public string CurrentMiles { get; set; }
        public string Status { get; set; }
        public string SCheck { get; set; }
        public string MCheck { get; set; }
        public string Total_Bill { get; set; }
    }
}
