//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Workshop_Automation_Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Vehicle_WorkShop_AutomationEntities : DbContext
    {
        public Vehicle_WorkShop_AutomationEntities()
            : base("name=Vehicle_WorkShop_AutomationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Mechanic> Mechanics { get; set; }
        public virtual DbSet<Mechanic_Service> Mechanic_Service { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Surveyor> Surveyors { get; set; }
        public virtual DbSet<Vehicle_Company> Vehicle_Company { get; set; }
        public virtual DbSet<Vehicle_Customer> Vehicle_Customer { get; set; }
        public virtual DbSet<Vehicle_Name> Vehicle_Name { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<App_Service> App_Service { get; set; }
    }
}
