//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Workshop_Automation_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}
